# Generated by Django 2.1.7 on 2019-04-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balanco',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('datahora_registro', models.DateTimeField()),
                ('Balanco', models.DecimalField(decimal_places=2, max_digits=17)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('datahora_registro', models.DateTimeField()),
                ('descricao', models.CharField(max_length=100)),
                ('origem', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=17)),
            ],
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('datahora_registro', models.DateTimeField()),
                ('descricao', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=17)),
            ],
        ),
    ]
