# Generated by Django 2.1.7 on 2019-07-17 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cliente', '0002_occurrencecall_servicerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deconto', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('pagamento_efetuado', models.BooleanField(default=False)),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('OS', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fatura_OS', to='Cliente.ServiceOrder')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fatura_cliente', to='Cliente.BasicInfo')),
            ],
        ),
    ]
