# Generated by Django 2.1.7 on 2019-04-12 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Financeiro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='descricao',
            new_name='classificacao',
        ),
        migrations.RenameField(
            model_name='saida',
            old_name='descricao',
            new_name='classificacao',
        ),
    ]
