# Generated by Django 2.1.7 on 2019-07-30 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Financeiro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatura',
            name='OS',
        ),
    ]
