# Generated by Django 2.1.7 on 2019-07-30 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Financeiro', '0002_remove_fatura_os'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fatura',
            old_name='deconto',
            new_name='desconto',
        ),
    ]
