# Generated by Django 2.1.7 on 2019-04-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financeiro', '0004_auto_20190412_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='percentual_desconto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
