# Generated by Django 2.1.7 on 2019-04-13 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Financeiro', '0005_auto_20190412_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='Cliente',
            new_name='cliente',
        ),
    ]
