# Generated by Django 2.1.7 on 2019-04-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financeiro', '0006_auto_20190412_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='percentual_desconto',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='valor',
            field=models.CharField(max_length=20),
        ),
    ]
