# Generated by Django 2.1.7 on 2019-04-13 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Financeiro', '0008_auto_20190413_0243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balanco',
            old_name='Balanco',
            new_name='balanco',
        ),
    ]
