# Generated by Django 2.1.7 on 2019-04-13 08:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Financeiro', '0009_auto_20190413_0438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='classificacao_servico',
            new_name='classificacao_receita',
        ),
        migrations.RenameField(
            model_name='saida',
            old_name='classificacao',
            new_name='classificacao_despesa',
        ),
        migrations.RemoveField(
            model_name='saida',
            name='destino',
        ),
        migrations.AddField(
            model_name='saida',
            name='data_vencimento',
            field=models.DateField(default=datetime.datetime(2019, 4, 13, 8, 16, 5, 471258, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saida',
            name='despesa_fixa',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saida',
            name='forma_pagamento',
            field=models.CharField(choices=[('Débito', 'Débito'), ('Crédito', 'Crédito'), ('Boleto', 'Boleto'), ('Dinheiro', 'Dinheiro')], default='Débito', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saida',
            name='observacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='saida',
            name='percentual_desconto',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='saida',
            name='produto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='saida',
            name='quantidade_produto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='saida',
            name='valor',
            field=models.CharField(max_length=20),
        ),
    ]
