# Generated by Django 2.1.7 on 2019-04-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financeiro', '0013_auto_20190424_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='forma_pagamento',
            field=models.CharField(choices=[('Débito', 'Cartão de Débito'), ('Crédito', 'Cartão de Crédito'), ('Boleto', 'Boleto'), ('Depósito', 'Depósito'), ('Transferência', 'Transferência'), ('Dinheiro', 'Dinheiro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='saida',
            name='forma_pagamento',
            field=models.CharField(choices=[('Débito', 'Cartão de Débito'), ('Crédito', 'Cartão de Crédito'), ('Boleto', 'Boleto'), ('Depósito', 'Depósito'), ('Transferência', 'Transferência'), ('Dinheiro', 'Dinheiro')], max_length=100),
        ),
    ]
