# Generated by Django 2.1.7 on 2019-04-29 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Financeiro', '0014_auto_20190424_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao_receita', models.CharField(max_length=100)),
                ('produto', models.CharField(blank=True, max_length=100, null=True)),
                ('quantidade_produto', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=20)),
                ('id_entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Financeiro.Entrada')),
            ],
        ),
    ]
