# Generated by Django 2.1.7 on 2019-04-30 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Financeiro', '0015_entradaprod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaprod',
            name='id_entrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Financeiro.Entrada'),
        ),
        migrations.AlterField(
            model_name='entradaprod',
            name='produto',
            field=models.CharField(default='TESTE', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entradaprod',
            name='quantidade_produto',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entradaprod',
            name='valor_unitario',
            field=models.CharField(max_length=20),
        ),
    ]
