# Generated by Django 2.1.7 on 2019-05-06 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Financeiro', '0017_auto_20190430_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaidaProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao_despesa', models.CharField(max_length=100)),
                ('produto', models.CharField(max_length=100)),
                ('quantidade_produto', models.CharField(max_length=100)),
                ('valor_unitario', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='saida',
            name='classificacao_despesa',
        ),
        migrations.RemoveField(
            model_name='saida',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='saida',
            name='quantidade_produto',
        ),
        migrations.AddField(
            model_name='saidaprod',
            name='id_saida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_produts', to='Financeiro.Saida'),
        ),
    ]
