# Generated by Django 2.1.7 on 2019-05-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financeiro', '0018_auto_20190506_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saida',
            name='percentual_desconto',
        ),
        migrations.AddField(
            model_name='entradaprod',
            name='valor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='saida',
            name='valor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
