# Generated by Django 2.1.7 on 2019-05-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financeiro', '0019_auto_20190506_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradaprod',
            name='valor',
        ),
        migrations.AddField(
            model_name='saida',
            name='percentual_desconto',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
