# Generated by Django 2.1.7 on 2019-05-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financeiro', '0020_auto_20190506_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='valor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
