# Generated by Django 2.1.7 on 2019-05-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financeiro', '0022_auto_20190510_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentosfixos',
            name='identificador_lancamento',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lancamentosfixos',
            name='observacao',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
