# Generated by Django 2.1.7 on 2019-06-10 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Financeiro', '0023_auto_20190517_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='data_vencimento',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='receita_fixa',
        ),
        migrations.RemoveField(
            model_name='saida',
            name='data_vencimento',
        ),
        migrations.RemoveField(
            model_name='saida',
            name='despesa_fixa',
        ),
    ]
