# Generated by Django 2.1.7 on 2019-05-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControleAdministrativo', '0002_remove_funcionarionivel_cargo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionariocargo',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='funcionarionivel',
            name='nivel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
