# Generated by Django 2.1.7 on 2019-07-24 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_url', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=500)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_creator', to=settings.AUTH_USER_MODEL)),
                ('receiver_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_receiver_group', to='auth.Group')),
                ('receiver_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_receiver_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
