# Generated by Django 2.1.7 on 2019-07-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notificacao', '0003_auto_20190723_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
