# Generated by Django 2.1.7 on 2019-07-17 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0002_occurrencecall_servicerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrencecall',
            name='occurrence',
        ),
    ]
