# Generated by Django 2.1.7 on 2019-05-29 23:18

import Cliente.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0004_auto_20190528_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='data_cadastro',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='data_fim_servico',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Fim de Serviço'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='data_inicio_servico',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Início de Serviço'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='data_ultima_modificacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Ultima Modificação'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='nome_local_servico',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Local do Serviço'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='nome_responsavel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Responsável'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='numero_documento_CNPJ',
            field=models.CharField(blank=True, max_length=18, null=True, validators=[Cliente.utilities.validateCNPJ], verbose_name='Número de CNPJ'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='numero_documento_CPF',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[Cliente.utilities.validateCPF], verbose_name='Número de CPF'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='quantidade_funcionarios_alocados',
            field=models.IntegerField(default=1, verbose_name='Qtd. Funcionários Alocados'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='servico_ativo',
            field=models.BooleanField(default=True, verbose_name='Serviço Ativo'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='tipo_pessoa',
            field=models.CharField(blank=True, choices=[('F', 'Física'), ('J', 'Jurídica')], max_length=1, null=True, verbose_name='Tipo de Pessoa'),
        ),
    ]
