# Generated by Django 2.1.7 on 2019-06-07 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0005_auto_20190529_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='basicinfo',
        ),
        migrations.RemoveField(
            model_name='addressinfo',
            name='end_servico',
        ),
        migrations.RemoveField(
            model_name='addressinfo',
            name='end_servico_CEP',
        ),
        migrations.RemoveField(
            model_name='addressinfo',
            name='end_servico_bairro',
        ),
        migrations.RemoveField(
            model_name='addressinfo',
            name='end_servico_complemento',
        ),
        migrations.RemoveField(
            model_name='addressinfo',
            name='end_servico_estado',
        ),
        migrations.RemoveField(
            model_name='addressinfo',
            name='end_servico_municipio',
        ),
        migrations.RemoveField(
            model_name='addressinfo',
            name='end_servico_numero',
        ),
        migrations.RemoveField(
            model_name='addressinfo',
            name='end_servico_pais',
        ),
        migrations.AddField(
            model_name='addressinfo',
            name='cont_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='addressinfo',
            name='cont_email_adicional',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='addressinfo',
            name='cont_tel_cel',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Entre Telefone no Formato: '(DDD)99999-9999'.", regex='^(\\+\\d{0,4})?(\\(\\d{0,3}\\))?([0-9\\-]{7,15})$')]),
        ),
        migrations.AddField(
            model_name='addressinfo',
            name='cont_tel_cel_adicional',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Entre Telefone no Formato: '(DDD)99999-9999'.", regex='^(\\+\\d{0,4})?(\\(\\d{0,3}\\))?([0-9\\-]{7,15})$')]),
        ),
        migrations.AddField(
            model_name='addressinfo',
            name='cont_tel_fixo',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Entre Telefone no Formato: '(DDD)99999-9999'.", regex='^(\\+\\d{0,4})?(\\(\\d{0,3}\\))?([0-9\\-]{7,15})$')]),
        ),
        migrations.AddField(
            model_name='addressinfo',
            name='cont_tel_fixo_adicional',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Entre Telefone no Formato: '(DDD)99999-9999'.", regex='^(\\+\\d{0,4})?(\\(\\d{0,3}\\))?([0-9\\-]{7,15})$')]),
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
