# Generated by Django 2.1.7 on 2019-07-18 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0006_auto_20190718_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerecord',
            name='uid',
        ),
        migrations.AlterUniqueTogether(
            name='servicerecord',
            unique_together={('data', 'LS')},
        ),
    ]
