# Generated by Django 2.1.7 on 2019-07-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0007_auto_20190718_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencecall',
            name='status',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('Fechado', 'Fechado'), ('Em andamento', 'Em Andamento')], default='Aberto', max_length=100),
            preserve_default=False,
        ),
    ]
