# Generated by Django 2.1.7 on 2019-07-17 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccurrenceCall',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(auto_now_add=True)),
                ('occurrence', models.IntegerField()),
                ('description', models.TextField()),
                ('LS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ServiceOccurence', to='Cliente.ServiceGround')),
            ],
        ),
    ]
