# Generated by Django 2.1.7 on 2019-07-22 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0009_occurrencecall_recreate'),
        ('Cliente', '0008_occurrencecall_status'),
    ]

    operations = [
    ]
