# Generated by Django 2.1.7 on 2019-06-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0009_auto_20190613_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='funcionarios',
            field=models.ManyToManyField(related_name='ordem_servico_funcionarios', to='Funcionario.BasicInfo'),
        ),
    ]
