# Generated by Django 2.1.7 on 2019-07-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0011_occurrencecall_status_recreate'),
        ('Cliente', '0010_merge_20190722_1435'),
    ]

    operations = [
    ]
