# Generated by Django 2.1.7 on 2019-06-18 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0011_auto_20190618_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceorder',
            old_name='servico_produto',
            new_name='produto',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='funcionarios',
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='data_emissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='servicos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordem_servico', to='Cliente.ServiceDescription'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
