# Generated by Django 2.1.7 on 2019-07-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0012_merge_20190722_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencecall',
            name='motive',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
