# Generated by Django 2.1.7 on 2019-06-18 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0012_auto_20190618_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='servicos',
        ),
        migrations.AddField(
            model_name='servicedescription',
            name='SO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descricao_servico_OS', to='Cliente.ServiceOrder'),
        ),
        migrations.AlterField(
            model_name='servicedescription',
            name='funcionario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descricao_servico_funcionario', to='Funcionario.BasicInfo'),
        ),
    ]
