# Generated by Django 2.1.7 on 2019-06-18 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0013_auto_20190618_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='subcategoria',
        ),
    ]
