# Generated by Django 2.1.7 on 2019-07-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0014_remove_occurrencecall_occurrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrencecall',
            name='status',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('Fechado', 'Fechado'), ('Em Andamento', 'Em Andamento')], max_length=100),
        ),
    ]
