# Generated by Django 2.1.7 on 2019-06-18 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0014_auto_20190618_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedescription',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descricao_servico_funcionario', to='Funcionario.BasicInfo'),
        ),
    ]
