# Generated by Django 2.1.7 on 2019-06-19 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0015_auto_20190618_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordem_servico_cliente', to='Cliente.BasicInfo', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='data_emissao',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Data de Emissão'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='faturado',
            field=models.BooleanField(default=False, verbose_name='Faturado'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='local_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordem_servico_ls', to='Cliente.ServiceGround', verbose_name='Local de Serviço'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='produto',
            field=models.BooleanField(default=False, verbose_name='Produto'),
        ),
    ]
