# Generated by Django 2.1.7 on 2019-06-21 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0016_auto_20190619_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='produto',
            field=models.BooleanField(default=False, verbose_name='Possui Produto ?'),
        ),
    ]
