# Generated by Django 2.1.7 on 2019-07-30 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Financeiro', '0002_remove_fatura_os'),
        ('Cliente', '0017_auto_20190722_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='fatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordem_servico_fatura', to='Financeiro.Fatura'),
        ),
    ]
