# Generated by Django 2.1.7 on 2019-06-21 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0017_auto_20190621_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='descricao',
        ),
        migrations.AddField(
            model_name='servicedescription',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='orbservacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
