# Generated by Django 2.1.7 on 2019-06-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0018_auto_20190621_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceorder',
            old_name='orbservacao',
            new_name='observacao',
        ),
        migrations.AlterField(
            model_name='servicedescription',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição'),
        ),
    ]
