# Generated by Django 2.1.7 on 2019-03-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='obs_desligamento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
