# Generated by Django 2.1.7 on 2019-03-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0002_auto_20190326_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='deficiente',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
