# Generated by Django 2.1.7 on 2019-03-30 23:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0003_auto_20190330_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='cont_tel_cel',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Entre Telefone no Formato: '+99(99)999999999'.", regex='^(\\+\\d{0,4})?(\\(\\d{0,3}\\))?(\\d{7,15})$')]),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='cont_tel_fixo',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Entre Telefone no Formato: '+99(99)999999999'.", regex='^(\\+\\d{0,4})?(\\(\\d{0,3}\\))?(\\d{7,15})$')]),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='cont_tel_recado',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Entre Telefone no Formato: '+99(99)999999999'.", regex='^(\\+\\d{0,4})?(\\(\\d{0,3}\\))?(\\d{7,15})$')]),
        ),
        migrations.AlterField(
            model_name='interninfo',
            name='estag_instituto_tel',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Entre Telefone no Formato: '+99(99)999999999'.", regex='^(\\+\\d{0,4})?(\\(\\d{0,3}\\))?(\\d{7,15})$')]),
        ),
    ]
