# Generated by Django 2.1.7 on 2019-03-27 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0003_basicinfo_deficiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentattachments',
            name='CPF',
            field=models.DecimalField(decimal_places=0, default=40503387851, max_digits=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentattachments',
            name='docscan_CPF',
            field=models.ImageField(blank=True, null=True, upload_to='<django.db.models.fields.DecimalField>\\%Y%m'),
        ),
        migrations.AlterField(
            model_name='documentattachments',
            name='docscan_CTPS',
            field=models.ImageField(blank=True, null=True, upload_to='<django.db.models.fields.DecimalField>\\%Y%m'),
        ),
        migrations.AlterField(
            model_name='documentattachments',
            name='docscan_CV',
            field=models.FileField(blank=True, null=True, upload_to='<django.db.models.fields.DecimalField>\\%Y%m'),
        ),
        migrations.AlterField(
            model_name='documentattachments',
            name='docscan_TE',
            field=models.ImageField(blank=True, null=True, upload_to='<django.db.models.fields.DecimalField>\\%Y%m'),
        ),
        migrations.AlterField(
            model_name='documentattachments',
            name='docscan_certidao_casamento',
            field=models.ImageField(blank=True, null=True, upload_to='<django.db.models.fields.DecimalField>\\%Y%m'),
        ),
        migrations.AlterField(
            model_name='documentattachments',
            name='docscan_certidao_nascimento',
            field=models.ImageField(blank=True, null=True, upload_to='<django.db.models.fields.DecimalField>\\%Y%m'),
        ),
        migrations.AlterField(
            model_name='documentattachments',
            name='docscan_comprovante_escolar',
            field=models.ImageField(blank=True, null=True, upload_to='<django.db.models.fields.DecimalField>\\%Y%m'),
        ),
        migrations.AlterField(
            model_name='documentattachments',
            name='docscan_comprovante_resid',
            field=models.ImageField(blank=True, null=True, upload_to='<django.db.models.fields.DecimalField>\\%Y%m'),
        ),
        migrations.AlterField(
            model_name='documentattachments',
            name='docscan_reservista',
            field=models.ImageField(blank=True, null=True, upload_to='<django.db.models.fields.DecimalField>\\%Y%m'),
        ),
    ]
