# Generated by Django 2.1.7 on 2019-03-27 00:58

import Funcionario.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0004_auto_20190326_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentattachments',
            name='CPF',
        ),
        migrations.AlterField(
            model_name='documentattachments',
            name='docscan_CPF',
            field=models.ImageField(blank=True, null=True, upload_to=Funcionario.utilities.user_media_path),
        ),
        migrations.AlterField(
            model_name='documentattachments',
            name='docscan_CTPS',
            field=models.ImageField(blank=True, null=True, upload_to=Funcionario.utilities.user_media_path),
        ),
        migrations.AlterField(
            model_name='documentattachments',
            name='docscan_CV',
            field=models.FileField(blank=True, null=True, upload_to=Funcionario.utilities.user_media_path),
        ),
        migrations.AlterField(
            model_name='documentattachments',
            name='docscan_TE',
            field=models.ImageField(blank=True, null=True, upload_to=Funcionario.utilities.user_media_path),
        ),
        migrations.AlterField(
            model_name='documentattachments',
            name='docscan_certidao_casamento',
            field=models.ImageField(blank=True, null=True, upload_to=Funcionario.utilities.user_media_path),
        ),
        migrations.AlterField(
            model_name='documentattachments',
            name='docscan_certidao_nascimento',
            field=models.ImageField(blank=True, null=True, upload_to=Funcionario.utilities.user_media_path),
        ),
        migrations.AlterField(
            model_name='documentattachments',
            name='docscan_comprovante_escolar',
            field=models.ImageField(blank=True, null=True, upload_to=Funcionario.utilities.user_media_path),
        ),
        migrations.AlterField(
            model_name='documentattachments',
            name='docscan_comprovante_resid',
            field=models.ImageField(blank=True, null=True, upload_to=Funcionario.utilities.user_media_path),
        ),
        migrations.AlterField(
            model_name='documentattachments',
            name='docscan_reservista',
            field=models.ImageField(blank=True, null=True, upload_to=Funcionario.utilities.user_media_path),
        ),
    ]
