# Generated by Django 2.1.7 on 2019-03-31 01:08

import Funcionario.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0004_auto_20190330_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='numero_documento_CPF',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True, validators=[Funcionario.utilities.validateCPF]),
        ),
    ]
