# Generated by Django 2.1.7 on 2019-03-27 01:31

import Funcionario.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0005_auto_20190326_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependente',
            name='docscan_CPF',
            field=models.ImageField(blank=True, null=True, upload_to=Funcionario.utilities.user_media_path_CPF),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='docscan_RG',
            field=models.ImageField(blank=True, null=True, upload_to=Funcionario.utilities.user_media_path_RG),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='docscan_certidao_nascimento',
            field=models.ImageField(blank=True, null=True, upload_to=Funcionario.utilities.user_media_path_CERTIDAONASCIMENTO),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='docscan_vacinacao',
            field=models.ImageField(blank=True, null=True, upload_to=Funcionario.utilities.user_media_path_VACINACAO),
        ),
        migrations.AlterField(
            model_name='documentattachments',
            name='docscan_CPF',
            field=models.ImageField(blank=True, null=True, upload_to=Funcionario.utilities.user_media_path_CPF),
        ),
        migrations.AlterField(
            model_name='documentattachments',
            name='docscan_CTPS',
            field=models.ImageField(blank=True, null=True, upload_to=Funcionario.utilities.user_media_path_CTPS),
        ),
        migrations.AlterField(
            model_name='documentattachments',
            name='docscan_CV',
            field=models.FileField(blank=True, null=True, upload_to=Funcionario.utilities.user_media_path_CV),
        ),
        migrations.AlterField(
            model_name='documentattachments',
            name='docscan_TE',
            field=models.ImageField(blank=True, null=True, upload_to=Funcionario.utilities.user_media_path_TE),
        ),
        migrations.AlterField(
            model_name='documentattachments',
            name='docscan_certidao_casamento',
            field=models.ImageField(blank=True, null=True, upload_to=Funcionario.utilities.user_media_path_CERTIDAOCASAMENTO),
        ),
        migrations.AlterField(
            model_name='documentattachments',
            name='docscan_certidao_nascimento',
            field=models.ImageField(blank=True, null=True, upload_to=Funcionario.utilities.user_media_path_CERTIDAONASCIMENTO),
        ),
        migrations.AlterField(
            model_name='documentattachments',
            name='docscan_comprovante_escolar',
            field=models.ImageField(blank=True, null=True, upload_to=Funcionario.utilities.user_media_path_COMPROVANTEESCOLAR),
        ),
        migrations.AlterField(
            model_name='documentattachments',
            name='docscan_comprovante_resid',
            field=models.ImageField(blank=True, null=True, upload_to=Funcionario.utilities.user_media_path_COMPROVANTERESIDENCIA),
        ),
        migrations.AlterField(
            model_name='documentattachments',
            name='docscan_reservista',
            field=models.ImageField(blank=True, null=True, upload_to=Funcionario.utilities.user_media_path_RESERVISTA),
        ),
    ]
