# Generated by Django 2.1.7 on 2019-03-31 01:19

import Funcionario.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0005_auto_20190330_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='numero_documento_CPF',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[Funcionario.utilities.validateCPF]),
        ),
    ]
