# Generated by Django 2.1.7 on 2019-03-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0006_auto_20190326_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
