# Generated by Django 2.1.7 on 2019-03-31 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0007_auto_20190330_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressinfo',
            name='end_CEP',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
