# Generated by Django 2.1.7 on 2019-03-31 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0009_auto_20190330_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interninfo',
            name='estag_instituto_CNPJ',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
