# Generated by Django 2.1.7 on 2019-04-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0011_auto_20190331_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractualinfo',
            name='contrat_cesta_valor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contractualinfo',
            name='contrat_salario_atual',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contractualinfo',
            name='contrat_salario_base',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contractualinfo',
            name='contrat_vale_alim_valor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contractualinfo',
            name='contrat_vale_comb_valor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contractualinfo',
            name='contrat_vale_ref_valor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contractualinfo',
            name='contrat_vale_transp_valor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
