# Generated by Django 2.1.7 on 2019-04-01 04:09

import Funcionario.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0012_auto_20190331_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='numero_documento_CPF',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[Funcionario.utilities.validateCPF]),
        ),
    ]
