# Generated by Django 2.1.7 on 2019-04-09 00:23

import Funcionario.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0014_auto_20190405_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='numero_documento_CPF',
            field=models.CharField(default=0, max_length=14, validators=[Funcionario.utilities.validateCPF]),
            preserve_default=False,
        ),
    ]
