# Generated by Django 2.1.7 on 2019-04-09 00:50

import Funcionario.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0015_auto_20190408_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, validators=[Funcionario.utilities.validateNoFutureDates]),
        ),
    ]
