# Generated by Django 2.1.7 on 2019-04-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0016_auto_20190408_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('CASADO', 'Casado(a)'), ('SOLTEIRO', 'Solteiro(a)'), ('VIUVO', 'Viuvo(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('UNIAO ESTAVEL', 'União Estável')], max_length=200, null=True),
        ),
    ]
