# Generated by Django 2.1.7 on 2019-04-09 22:19

import Funcionario.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0017_auto_20190409_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractualinfo',
            name='contrat_data_admissao',
            field=models.DateField(blank=True, null=True, validators=[Funcionario.utilities.validateNoFutureDates]),
        ),
        migrations.AlterField(
            model_name='documentsinfo',
            name='docs_CNH_data_emissao',
            field=models.DateField(blank=True, null=True, validators=[Funcionario.utilities.validateNoFutureDates]),
        ),
        migrations.AlterField(
            model_name='documentsinfo',
            name='docs_CNH_data_primeira',
            field=models.DateField(blank=True, null=True, validators=[Funcionario.utilities.validateNoFutureDates]),
        ),
        migrations.AlterField(
            model_name='documentsinfo',
            name='docs_CTPS_data_emissao',
            field=models.DateField(blank=True, null=True, validators=[Funcionario.utilities.validateNoFutureDates]),
        ),
        migrations.AlterField(
            model_name='documentsinfo',
            name='docs_OC_data_emissao',
            field=models.DateField(blank=True, null=True, validators=[Funcionario.utilities.validateNoFutureDates]),
        ),
        migrations.AlterField(
            model_name='documentsinfo',
            name='docs_RG_data_emissao',
            field=models.DateField(blank=True, null=True, validators=[Funcionario.utilities.validateNoFutureDates]),
        ),
        migrations.AlterField(
            model_name='documentsinfo',
            name='docs_RNE_data_emissao',
            field=models.DateField(blank=True, null=True, validators=[Funcionario.utilities.validateNoFutureDates]),
        ),
        migrations.AlterField(
            model_name='interninfo',
            name='estag_data_inicio',
            field=models.DateField(blank=True, null=True, validators=[Funcionario.utilities.validateNoFutureDates]),
        ),
    ]
