# Generated by Django 2.1.7 on 2019-04-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0019_auto_20190409_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='ferias',
            field=models.BooleanField(default=False),
        ),
    ]
