# Generated by Django 2.1.7 on 2019-04-10 02:27

import Funcionario.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0020_basicinfo_ferias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='numero_documento_CPF',
            field=models.CharField(error_messages={'unique': 'CPF Já Registrado'}, max_length=14, unique=True, validators=[Funcionario.utilities.validateCPF]),
        ),
        migrations.AlterField(
            model_name='foreignerinfo',
            name='estr_data_chegada',
            field=models.DateField(blank=True, null=True, validators=[Funcionario.utilities.validateNoFutureDates]),
        ),
        migrations.AlterField(
            model_name='foreignerinfo',
            name='estr_data_naturalizacao',
            field=models.DateField(blank=True, null=True, validators=[Funcionario.utilities.validateNoFutureDates]),
        ),
    ]
