# Generated by Django 2.1.7 on 2019-04-10 02:29

import Funcionario.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0021_auto_20190409_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressinfo',
            name='end_CEP',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[Funcionario.utilities.validateCEP]),
        ),
        migrations.AlterField(
            model_name='interninfo',
            name='estag_instituto_CEP',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[Funcionario.utilities.validateCEP]),
        ),
    ]
