# Generated by Django 2.1.7 on 2019-04-10 02:54

import Funcionario.utilities
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0022_auto_20190409_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotherjobinfo',
            name='vinc_outra_emp_CNPJ',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, validators=[Funcionario.utilities.validateCNPJ]),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='cont_tel_cel',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Entre Telefone no Formato: '(DDD)99999-9999'.", regex='^(\\+\\d{0,4})?(\\(\\d{0,3}\\))?([0-9\\-]{7,15})$')]),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='cont_tel_fixo',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Entre Telefone no Formato: '(DDD)99999-9999'.", regex='^(\\+\\d{0,4})?(\\(\\d{0,3}\\))?([0-9\\-]{7,15})$')]),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='cont_tel_recado',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Entre Telefone no Formato: '(DDD)99999-9999'.", regex='^(\\+\\d{0,4})?(\\(\\d{0,3}\\))?([0-9\\-]{7,15})$')]),
        ),
        migrations.AlterField(
            model_name='interninfo',
            name='estag_instituto_tel',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Entre Telefone no Formato: '(DDD)99999-9999'.", regex='^(\\+\\d{0,4})?(\\(\\d{0,3}\\))?([0-9\\-]{7,15})$')]),
        ),
    ]
