# Generated by Django 2.1.7 on 2019-04-10 02:56

import Funcionario.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0023_auto_20190409_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotherjobinfo',
            name='vinc_outra_emp_CNPJ',
            field=models.CharField(blank=True, max_length=18, null=True, validators=[Funcionario.utilities.validateCNPJ]),
        ),
    ]
