# Generated by Django 2.1.7 on 2019-04-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0025_auto_20190410_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='data_ultima_ativacao',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='data_ultimo_desligamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
