# Generated by Django 2.1.7 on 2019-04-10 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0026_auto_20190410_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='data_ultima_modificacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='data_ultima_ativacao',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='data_ultimo_desligamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
