# Generated by Django 2.1.7 on 2019-04-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0028_auto_20190412_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='data_ultima_modificacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
