# Generated by Django 2.1.7 on 2019-04-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0029_auto_20190412_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='SEG',
            field=models.BooleanField(default=True),
        ),
    ]
