# Generated by Django 2.1.7 on 2019-04-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0030_basicinfo_seg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractualinfo',
            name='contrat_cargo_inicial',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='positioninfo',
            name='funcao_cargo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
