# Generated by Django 2.1.7 on 2019-04-17 21:44

import Funcionario.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0031_auto_20190417_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='numero_documento_CPF',
            field=models.CharField(max_length=14, validators=[Funcionario.utilities.validateCPF]),
        ),
        migrations.AlterField(
            model_name='contractualinfo',
            name='contrat_cargo_inicial',
            field=models.CharField(blank=True, choices=[('Auxiliar Administrativo', 'Auxiliar Administrativo'), ('Segurança', 'Segurança')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='positioninfo',
            name='funcao_cargo',
            field=models.CharField(blank=True, choices=[('Auxiliar Administrativo', 'Auxiliar Administrativo'), ('Segurança', 'Segurança')], max_length=200, null=True),
        ),
    ]
