# Generated by Django 2.1.7 on 2019-04-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0033_auto_20190417_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractualinfo',
            name='contrat_cargo_inicial',
            field=models.CharField(blank=True, choices=[('Auxiliar Administrativo', 'Auxiliar Administrativo'), ('Segurança', 'Segurança'), ('Limpeza e Manutenção', 'Limpeza e Manutenção')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='positioninfo',
            name='funcao_cargo',
            field=models.CharField(blank=True, choices=[('Auxiliar Administrativo', 'Auxiliar Administrativo'), ('Segurança', 'Segurança'), ('Limpeza e Manutenção', 'Limpeza e Manutenção')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='positioninfo',
            name='funcao_nivel',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1, null=True),
        ),
    ]
