# Generated by Django 2.1.7 on 2019-04-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0034_auto_20190417_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positioninfo',
            name='funcao_cargo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
