# Generated by Django 2.1.7 on 2019-04-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0035_auto_20190417_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positioninfo',
            name='funcao_cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='positioninfo',
            name='funcao_nivel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
