# Generated by Django 2.1.7 on 2019-04-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0036_auto_20190417_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractualinfo',
            name='contrat_cargo_inicial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
