# Generated by Django 2.1.7 on 2019-05-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0038_auto_20190516_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankinginfo',
            name='banco_agencia',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
