# Generated by Django 2.1.7 on 2019-05-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0040_auto_20190517_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='obs_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
