# Generated by Django 2.1.7 on 2019-06-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0044_auto_20190604_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependente',
            name='grau_parentesco',
            field=models.CharField(blank=True, choices=[('1', 'Cônjuge'), ('2', 'Companheiro (a) com o (a) qual tenha filhos ou viva a mais de 05 anos ou possua Declaração de união Estável '), ('3', 'Filho(a) ou Enteado(a)'), ('4', 'Filho(a) ou Enteado(a), universitario(a) ou cursando escola técnica de 2º Grau'), ('5', 'Irmão(ã), Neto(a) ou Bisneto(a) sem arrimo dos pais, do(a) qual detenha a guarda judicial '), ('6', 'Irmão(ã), Neto(a) ou Bisneto(a) sem arrimo dos pais, universitário(a) ou cursando escola técnica de 2º Grau do(a) qual detenha Guarda Judicial'), ('7', 'Pais, avós e bisavós'), ('8', 'Menor pobre do qual detenha guarda judicial'), ('9', 'A pessoa absolutamente incapaz, do qual seja tutor ou curador'), ('10', 'Ex-Cônjuge')], max_length=500, null=True),
        ),
    ]
