# Generated by Django 2.1.7 on 2019-06-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0045_auto_20190605_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependente',
            name='CPF',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
