# Generated by Django 2.1.7 on 2019-06-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0047_auto_20190605_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positioninfo',
            name='basicinfo',
        ),
        migrations.AddField(
            model_name='contractualinfo',
            name='contrat_funcao_CBO',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contractualinfo',
            name='contrat_funcao_cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contractualinfo',
            name='contrat_funcao_descricao',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='contractualinfo',
            name='contrat_funcao_gestor',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractualinfo',
            name='contrat_funcao_nivel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='PositionInfo',
        ),
    ]
