# Generated by Django 2.1.7 on 2019-06-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0048_auto_20190605_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractualinfo',
            name='contrat_funcao_nivel_inicial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
