# Generated by Django 2.1.7 on 2019-06-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0050_contractualinfo_contrat_data_ultima_alteracao_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='interninfo',
            name='estag_instituto_end_municipio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='interninfo',
            name='estag_instituto_end_numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
