# Generated by Django 2.1.7 on 2019-06-11 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0053_auto_20190611_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotherjobinfo',
            name='basicinfo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='another_job', serialize=False, to='Funcionario.BasicInfo'),
        ),
        migrations.AlterField(
            model_name='anotherjobinfo',
            name='vinc_comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractualinfo',
            name='contrat_funcao_descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interninfo',
            name='basicinfo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='intern_info', serialize=False, to='Funcionario.BasicInfo'),
        ),
    ]
