# Generated by Django 2.1.7 on 2019-06-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0054_auto_20190611_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='categoria',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='valor_hora_custo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='valor_hora_receita',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
